---

- hosts: all
  become: true
  roles:
    - base

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: web_server
  become: true
  roles:
    - web_server

- hosts: workstations
  become: true
  roles:
    - workstations
